---
title: "Figure 6"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Figure 6}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(princti)
library(tidyverse)
library(patchwork)
library(RColorBrewer)
```

```{r}
scaling_levels <- c(
  'Theory (NTK)',
  'Lazy',
  'Rich',
  'Very rich'
)
scaling_palette <- c(
  'darkgreen',
  '#1e996fff',
  '#e5c700ff',
  '#cc9f28ff'
)
```


```{r}
get_p1 <- function(n) {
  if(n==2) {
    tbl <- expand.grid(
      item=1:2, order=c('first', 'second')
    ) %>%
      as_tibble() %>%
      mutate(
        value = if_else(
          ((item==1) & (order=='first')) | ((item==2) & (order=='second')), 0.5, 0.
        )
      )
  }
  else{
    tbl <- get_p1(n-1)
    if(n%%4==3) {
      tbl <- bind_rows(
        tbl, tibble(item = n, order = c('first', 'second'), value=c(-0.5, 0.5))
      ) %>%
        mutate(
          value = case_when(
            (item==n-2) & (order == 'second') ~ -0.5,
            (item==n-1) & (order == 'first') ~ 0.5,
            TRUE ~ value
          )
        )
    }
    if(n%%4==0){
      tbl <- bind_rows(
        tbl, tibble(item = n, order = c('first', 'second'), value=c(-0.5, 0.))
      )
    }
    if(n%%4==1) {
      tbl <- bind_rows(
        tbl, tibble(item = n, order = c('first', 'second'), value=c(0., 0.))
      )
    }
    if(n%%4==2) {
      tbl <- bind_rows(
        tbl, tibble(item = n, order = c('first', 'second'), value=c(0., 0.5))
      ) %>%
        mutate(
          value = case_when(
            (item==n-2) & (order == 'second') ~ -0.5,
            (item==n-1) & (order == 'first') ~ 0.5,
            TRUE ~ value
          )
        )
    }
  }
  tbl %>% arrange(item, order)
}
get_p2 <- function(n) {
  if(n==2) {
    tbl <- expand.grid(
      item=1:2, order=c('first', 'second'), value=0.
    ) %>%
      as_tibble()
  }
  else{
    tbl <- get_p2(n-1)
    if(n%%4==1) {
      tbl <- bind_rows(
        tbl, tibble(item = n, order = c('first', 'second'), value=c(-0.5, 0.5))
      ) %>%
        mutate(
          value = case_when(
            (item==n-2) & (order == 'second') ~ -0.5,
            (item==n-1) & (order == 'first') ~ 0.5,
            TRUE ~ value
          )
        )
    }
    if(n%%4==2){
      tbl <- bind_rows(
        tbl, tibble(item = n, order = c('first', 'second'), value=c(-0.5, 0.))
      )
    }
    if(n%%4==3) {
      tbl <- bind_rows(
        tbl, tibble(item = n, order = c('first', 'second'), value=c(0., 0.))
      )
    }
    if(n%%4==0) {
      tbl <- bind_rows(
        tbl, tibble(item = n, order = c('first', 'second'), value=c(0., 0.5))
      ) %>%
        mutate(
          value = case_when(
            (item==n-2) & (order == 'second') ~ -0.5,
            (item==n-1) & (order == 'first') ~ 0.5,
            TRUE ~ value
          )
        )
    }
  }
  tbl %>% arrange(item, order)
}
get_p_network <- function(n) {
  p1 <- get_p1(n)
  p2 <- get_p2(n)
  bind_rows(
    p1 %>% mutate(unit='p1+', sign=1),
    p1 %>% mutate(order = if_else(order=='first', 'second', 'first'), unit='p1-', sign=-1),
    p2 %>% mutate(unit='p2+', sign=1),
    p2 %>% mutate(order = if_else(order=='first', 'second', 'first'), unit='p2-', sign=-1)
  )
}
```

```{r}
similarity <-
  time_traj_ti_similarity %>%
  filter((type == 'after training') | (scaling == 1.), i1 <= 2, i2 <= 2, j1 <= 2, j2 <= 2, features=='linear readout') %>%
  mutate(
    type = case_when(
      type == 'before training' ~ 'At initialization',
      scaling == 1. ~ 'Lazy',
      scaling == 1e-6 ~ 'Rich',
      TRUE ~ 'Very rich'
    )
  ) %>%
  bind_rows(
    expand.grid(i1 = 0:2, i2=0:2, j1=0:2, j2=0:2) %>%
      as_tibble() %>%
      mutate(
        type = 'Rank rep.\n(hypothetical)',
        distance = 1/2*(((gd_rank(j2+1, alpha=0.1)-gd_rank(j1+1, alpha=0.1))/(gd_rank(3, alpha=0.1)-gd_rank(1, alpha=0.1)))**2+((gd_rank(i2+1, alpha=0.1)-gd_rank(i1+1, alpha=0.1))/(gd_rank(3, alpha=0.1)-gd_rank(1, alpha=0.1)))**2)
      )
  ) %>%
  mutate(
    data_type = case_when(
      (i1 == i2) & (j1 == j2) ~ 'same',
      (i1 == i2) | (j1==j2) ~ 'overlapping',
      TRUE ~ 'distinct'
    )
  ) %>%
  mutate(
    j1 = map_chr(j1, ~LETTERS[.+1]) %>%
      factor(levels = LETTERS[1:7]),
    j2 = map_chr(j2, ~LETTERS[.+1]) %>%
      factor(levels = LETTERS[7:1]),
    i1 = map_chr(i1, ~LETTERS[.+1]) %>%
      factor(levels = LETTERS[1:7]),
    i2 = map_chr(i2, ~LETTERS[.+1]) %>%
      factor(levels = LETTERS[7:1]),
    x1 = paste0(i1, j1),
    x2 = paste0(i2, j2) %>%
      as.factor() %>%
      fct_rev(),
    type = factor(type, levels = c('Rank rep.\n(hypothetical)', 'At initialization', 'Lazy', 'Rich', 'Very rich'))
  ) %>%
  group_by(x1, x2, type) %>%
  summarise(distance = mean(distance)) %>%
  ggplot(aes(x1, x2, fill = distance)) +
  geom_tile() +
  theme_princti() +
  scale_y_discrete() +
  scale_x_discrete() +
  coord_equal() +
  scale_fill_gradient(low='black', high='white', breaks=c(0, 1), limits=c(0,1)) +
  labs(x = 'Trial 1', y = 'Trial 2', fill = 'Distance') +
  facet_wrap(~type, nrow=1) +
  theme(axis.text.x = element_text(angle=90, vjust=.5))
similarity
```
## Similarity fits

```{r}
similarity_fit <-
  rsa %>%
  filter((type == 'after training') | (scaling == 1.)) %>%
  mutate(
    type = case_when(
      type == 'before training' ~ 'At initialization',
      scaling == 1. ~ 'Lazy',
      scaling == 1e-6 ~ 'Rich',
      TRUE ~ 'Very rich'
    )
  ) %>%
  filter(params != 'intercept', type != 'At initialization') %>%
  mutate(
    params = factor(params, levels = c('all', 'add', 'rank', 'rank_diff'))
  ) %>%
  ggplot(aes(params, 1-loss, color=type, group=paste(type, features))) +
  stat_summary(geom='linerange', show.legend = FALSE) +
  stat_summary(geom='point', show.legend = FALSE, shape=16) +
  stat_summary(geom='line') +
  #scale_x_discrete(labels = c('All', '\nOverlap', 'Rank', '\nOutput'), breaks= c('all', 'add', 'rank', 'label')) +
  scale_color_manual(values = scaling_palette[2:4]) +
  theme_princti() +
  facet_wrap(~features, nrow=3) +
  #scale_y_continuous(breaks=c(0,1)) +
  labs(x = NULL, y = 'Variance\nExplained', color=NULL)
similarity_fit
```

```{r}
alpha_ntk <- get_alphas(1,1,0)[[2]]
df <-
  time_traj_ti %>%
  select(epoch, model_seed, j, k, margin, scaling) %>%
  inner_join(
    time_traj_ti_lr %>%
      select(model_seed, scaling, lr) %>%
      unique()
  ) %>%
  mutate(
    t = epoch*lr/6*(3572-1136),
    pred = gd_margin(j+1, k+1, t=t, alpha = alpha_ntk),
    error = (pred-margin)**2,
    scaling = case_when(
      scaling == 1 ~ 'Lazy',
      scaling == 1e-6 ~ 'Rich',
      abs(log(scaling, base=10)+32)<0.01 ~ 'Very rich'
    ) %>%
      factor(
        levels = scaling_levels
      )
  ) %>%
  select(-lr, -t)
df_last <-
  df %>%
  group_by(model_seed, scaling) %>%
  summarise(epoch = max(epoch)) %>%
  inner_join(df)
df_err <-
  expand.grid(
    epoch = 0:2000,
    model_seed = 0:19,
    j = 0:6,
    k = 0:6,
    scaling = c(
      'Lazy',
      'Rich',
      'Very rich'
    ) %>%
      factor(levels = scaling_levels)
  ) %>%
  as_tibble() %>%
  full_join(df) %>%
  full_join(df_last %>% select(-epoch, -margin, -pred) %>% rename(last_error = error)) %>%
  mutate(
    error = if_else(is.na(error), last_error, error)
  ) %>%
  select(-last_error)
```

```{r}
fig_error <-
  df_err %>%
  group_by(epoch, model_seed, scaling) %>%
  summarise(error = mean(error)) %>%
  ggplot(aes(epoch, error, color=scaling, fill=scaling, group=scaling, fill=scaling)) +
  stat_summary(geom='ribbon', color=NA, alpha=0.3, show.legend=FALSE, fun.ymin = function(x) mean(x)-sd(x), fun.ymax = function(x) mean(x)+sd(x)) +
  stat_summary(geom='line', show.legend=FALSE) +
  scale_x_continuous(trans='log1p') +
  coord_cartesian(xlim = c(0, 300)) +
  theme_princti() +
  labs(x = 'Training epoch', y = 'Error of NTK pred.', color = NULL, fill=NULL) +
  scale_color_manual(values = scaling_palette[2:4], drop = TRUE) +
  scale_fill_manual(values = scaling_palette[2:4], drop = TRUE) +
  scale_x_continuous(breaks = c(0, 300))
fig_error
```

```{r}
lines_df <-
  tibble(
    scaling = c(1, 1e-6, 1e-32),
    scaling_name = c(
      'Lazy',
      'Rich',
      'Very rich'
    ) %>%
      factor(levels = scaling_levels)
  )
fig_margin <-
  ti_scaling %>%
  filter(abs(k-j) > 1) %>%
  group_by(scaling, model_seed) %>%
  summarise(margin = mean(sign(k-j)*margin)) %>%
  ggplot(aes(sqrt(scaling), margin)) +
  geom_vline(mapping = aes(xintercept = sqrt(scaling), color=scaling_name), data=lines_df, show.legend=FALSE, alpha=0.5) +
  stat_summary(geom='line') +
  stat_summary(geom='ribbon', alpha = 0.3, fun.ymin = function(x) {mean(x)-sd(x)}, fun.ymax = function(x) {mean(x)+sd(x)}) +
  scale_x_continuous(
    trans = scales::trans_new(
      name = 'reverse_log10',
      transform = function(x) {-log(x, base=10)},
      inverse = function(x) {10**(-x)}
    ),
    breaks = c(1, 1e-16),
    labels = c('1', parse(text='10^{-16}'))
  ) +
  scale_color_manual(values = scaling_palette, labels = scaling_levels, drop = FALSE) +
  scale_y_continuous(n.breaks = 3) +
  labs(x = 'Scale', y = 'Test margin') +
  theme_princti()
fig_margin
```

```{r}
fig_acc <-
  ti_scaling %>%
  filter(abs(k-j) > 1) %>%
  group_by(scaling, model_seed) %>%
  summarise(margin = mean(sign(k-j)==sign(margin))) %>%
  ggplot(aes(sqrt(scaling), margin)) +
  geom_vline(mapping = aes(xintercept = sqrt(scaling), color=scaling_name), data=lines_df, show.legend=FALSE, alpha=0.5) +
  stat_summary(geom='line') +
  stat_summary(geom='ribbon', alpha = 0.3, fun.ymin = function(x) {mean(x)-sd(x)}, fun.ymax = function(x) {mean(x)+sd(x)}) +
  #stat_summary(geom='point') +
  #geom_point() +
  scale_x_continuous(
    trans = scales::trans_new(
      name = 'reverse_log10',
      transform = function(x) {-log(x, base=10)},
      inverse = function(x) {10**(-x)}
    ),
    breaks = c(1e-16, 1),
    labels = c(parse(text='10^{-16}'), '1')
  ) +
  scale_color_manual(values = scaling_palette, labels = scaling_levels, drop = FALSE) +
  scale_y_continuous(n.breaks = 3, limits=c(0.75, 1)) +
  labs(x = 'Scale', y = 'Test acc.') +
  theme_princti()
fig_acc
```

```{r}
df_last <-
  df_last %>%
  bind_rows(
    expand.grid(
      j = 1:7,
      k = 1:7
    ) %>%
      as_tibble() %>%
      dplyr::mutate(
        scaling = 'Theory (NTK)',
        margin = gd_margin(j, k, alpha=alpha_ntk),
        j = j-1,
        k = k-1
      )
  ) %>%
  filter(j != k) %>%
  mutate(
      label = map2_chr(j, k, ~paste0(min(LETTERS[..1+1],LETTERS[..2+1]), max(LETTERS[..1+1], LETTERS[..2+1]))),
      symbolic_distance = abs(k-j),
      margin = sign(k-j)*margin,
    symbolic_distance = if_else(symbolic_distance==1, 'SD: 1', as.character(symbolic_distance)) %>%
      factor(levels = c('SD: 1', as.character(2:6))),
    correct = if_else(margin > 0, 'yes', 'no')
  )
fig_gen <-
  df_last %>%
  ggplot(aes(label, margin, group=scaling, color=scaling)) +
  geom_hline(yintercept = 0, linetype='dashed') +
  stat_summary(mapping = aes(shape = correct), geom='point', size=2.5, show.legend = FALSE, data = df_last %>% filter(scaling != 'Theory (NTK)')) +
  stat_summary(geom='ribbon', alpha=0.3, color=NA, fill='grey80', show.legend=FALSE, fun.ymin = function(x) {mean(x)-sd(x)}, fun.ymax = function(x) {mean(x)+sd(x)}) +
  stat_summary(geom='line', data = df_last %>% filter(scaling != 'Theory (NTK)'), show.legend = TRUE, size=1.5) +
  stat_summary(mapping = aes(shape = correct), geom='point', size=2.5, show.legend = FALSE, data = df_last %>% filter(scaling == 'Theory (NTK)')) +
  stat_summary(geom='line', data = df_last %>% filter(scaling == 'Theory (NTK)'), show.legend = FALSE, linetype = '11', size=1.5) +
  facet_grid(~symbolic_distance, scales='free_x', space='free', switch = 'x') +
  theme_princti() +
  labs(x = 'Item pair', y = 'Margin', color = NULL, linetype = NULL) +
  scale_color_manual(values = scaling_palette %>% magrittr::set_names(scaling_levels), drop = FALSE) +
  scale_y_continuous(breaks = c(0,1,2)) +
  scale_shape_manual(values = c(yes = 16, no = 1), breaks=NULL) +
  scale_x_discrete(labels=c()) +
  theme(
    strip.placement = 'outside'
  )
```

```{r}
fig_g <-
  dnn_norms %>%
  ggplot(aes(sqrt(scaling), l2/sqrt(2))) + # We provided normalized vectors as inputs (i.e. divided by sqrt(2)), but it's easier to describe everything with onehot inputs
  stat_summary(geom='line') +
  stat_summary(geom='ribbon', alpha = 0.3, color='transparent', fun.ymin = function(x) {mean(x)-sd(x)}, fun.ymax = function(x) {mean(x)+sd(x)}) +
  #stat_summary(geom='point') +
  #geom_point() +
  scale_x_continuous(
    trans = scales::trans_new(
      name = 'reverse_log10',
      transform = function(x) {-log(x, base=10)},
      inverse = function(x) {10**(-x)}
    ),
    breaks = c(1e-16, 1),
    labels = c(parse(text='10^{-16}'), '1')
  ) +
  labs(x = 'Scale', y = 'L2-norm') +
  #scale_color_manual(breaks = c('dense', 'symmetric', 'modular'), values = c(scaling_palette[4], hcl.colors(3, palette = 'Dark 3')[c(1,3)])) +
  scale_y_log10(breaks = c(20, 1e4), labels = c('20', parse(text='10^{4}'))) +
  theme_princti() +
  theme(legend.position = c(0.8, 0.8))
fig_g
```

```{r}
fig_h <-
  inertia %>%
  filter(symmetric_input_weights == 'False', cl<=10, n==7) %>%
  mutate(
    inertia = if_else(cl==0, 1., inertia),
    scaling = case_when(
      scaling == '1.0' ~ 'Lazy',
      scaling == '1e-32' ~ 'Rich'
    ) %>%
      factor(
        levels = scaling_levels
      )
  ) %>%
  ggplot(aes(2*cl, inertia, color=scaling, fill=scaling, group=scaling, fill=scaling)) +
  stat_summary(geom='ribbon', color=NA, alpha=0.3, show.legend=FALSE, fun.ymin = function(x) mean(x)-3*sd(x), fun.ymax = function(x) mean(x)+3*sd(x)) +
  stat_summary(geom='line', show.legend=TRUE) +
  theme_princti() +
  labs(x = '# Clusters', y = 'Inertia', color = NULL, fill=NULL) +
  scale_color_manual(values = scaling_palette[2:4], drop = TRUE) +
  scale_fill_manual(values = scaling_palette[2:4], drop = TRUE) +
  scale_x_continuous(breaks = c(6, 20)) +
  scale_y_continuous(breaks = c(0,1))
fig_h
```

```{r}
dat <-
  clusters %>%
  filter(symmetric_input_weights=='False', scaling=='1e-32', n==7, n_clusters==3) %>%
  rename(order=arg) %>%
  mutate(item=j+1,unit = as.character(1+dim0%%n_clusters), value=array/(2*n_clusters)/sqrt(2)) %>%
  select(-dim0, -dim1, -n, -array, -j)
inner_join(
  dat %>% rename(seed1=seed, unit1=unit, value1=value),
  dat %>% rename(seed2=seed, unit2=unit, value2=value)
) %>%
  group_by(seed1, seed2, unit1, unit2, sign) %>%
  summarise(
    mismatch = sum((value1-value2)**2)
  ) %>%
  group_by(seed1, seed2, unit1, sign) %>%
  summarise(unit = unit2[which.min(mismatch)], mismatch=min(mismatch)) %>%
  filter(seed1!=seed2) %>%
  ggplot(aes(mismatch)) +
  geom_histogram()
assignment <-
  inner_join(
    dat %>% rename(seed1=seed, unit1=unit, value1=value),
    dat %>% rename(seed2=seed, unit2=unit, value2=value)
  ) %>%
  group_by(seed1, seed2, unit1, unit2, sign) %>%
  summarise(
    mismatch = sum((value1-value2)**2)
  ) %>%
  group_by(seed1, seed2, unit1, sign) %>%
  summarise(unit = unit2[which.min(mismatch)]) %>%
  filter(seed1==0) %>%
  ungroup() %>%
  select(-seed1) %>%
  rename(std_unit=unit1, seed=seed2)
assignment
```

```{r}
fig_i <-
  bind_rows(
    clusters %>%
      filter(symmetric_input_weights=='False', scaling=='1e-32', n==7, sign==1, n_clusters==3) %>%
      rename(order=arg) %>%
      mutate(item=j+1,unit = as.character(1+dim0%%n_clusters), value=array/(2*n_clusters)/sqrt(2)) %>%
      inner_join(assignment),
    get_p_network(7) %>%
      filter(unit %in% c('p1+', 'p2+')) %>%
      mutate(std_unit = unit)
  ) %>%
  mutate(
    item = map_chr(item, ~LETTERS[.]),
    assignment = if_else(std_unit %in% c('1', 'p1+'), 'p1+', 'p2+'),
    unit = factor(unit)
  ) %>%
  arrange(desc(unit)) %>%
  ggplot(aes(item, value, color=factor(std_unit), group=paste(std_unit,order))) +
  stat_summary(geom='ribbon', color=NA, alpha=0.3, fill='grey', show.legend=FALSE, fun.ymin = function(x) mean(x)-sd(x), fun.ymax = function(x) mean(x)+sd(x)) +
  stat_summary(geom='line', show.legend=TRUE) +
  #stat_summary(geom='point', show.legend=FALSE) +
  facet_grid(assignment~order) +
  theme_princti() +
  theme(strip.background = element_blank(),
  strip.text.x = element_blank()) +
  scale_color_manual(
    values = c(c(`p1+` = 'black', `p2+` = 'grey40'), colorspace::qualitative_hcl(h = c(0, 300, c = c(90, 90), l = 50), n=3) %>% magrittr::set_names(1:3))
  ) +
  labs(x = 'Item', y = 'Weight', color = 'Unit')
fig_i
```

```{r}
fig_j <-
  bind_rows(
    clusters %>%
      filter(symmetric_input_weights=='False', scaling=='1e-32', n==7, n_clusters==3) %>%
      rename(order=arg) %>%
      mutate(item=j+1,unit = as.character(1+dim0%%n_clusters), value=array/(2*n_clusters)/sqrt(2)) %>%
      inner_join(assignment),
    get_p_network(7) %>%
      mutate(std_unit = unit) %>%
      filter(unit %in% c('p1+', 'p2+'))
  ) %>%
  group_by(sign, std_unit, seed) %>%
  nest() %>%
  mutate(data = map(data, function(dat) {
    expand.grid(j1=1:7, j2=1:7) %>%
      inner_join(
        dat %>%
          filter(order=='first') %>%
          transmute(arr1=value, j1=item)
      ) %>%
      inner_join(
        dat %>%
          filter(order == 'second') %>%
          transmute(arr2=value, j2=item)
      ) %>%
      mutate(
        value = arr1+arr2,
        value = if_else(value>=0, value, 0)
      ) %>%
      select(j1, j2, value)
  })) %>%
  unnest() %>%
  mutate(value = sign*value) %>%
  filter(j2==j1+1) %>%
  mutate(
    label = map2_chr(j1, j2, ~paste0(LETTERS[..1], LETTERS[..2])),
    assignment = if_else(std_unit %in% c('1', 'p1+'), 'p1+', 'p2+'),
    unit = factor(std_unit)
  ) %>%
  ggplot(aes(label, value, color=unit, group=paste(unit,sign), linetype=factor(sign, levels=c(1,-1)))) +
  stat_summary(geom='ribbon', color=NA, alpha=0.3, fill='grey', show.legend=FALSE, fun.ymin = function(x) mean(x)-sd(x), fun.ymax = function(x) mean(x)+sd(x)) +
  stat_summary(geom='line', show.legend=TRUE) +
  #stat_summary(geom='point', show.legend=FALSE) +
  facet_wrap(~assignment, ncol=1) +
  theme_princti() +
  scale_color_manual(
    values = c(c(`p1+` = 'black', `p2+` = 'grey40'), colorspace::qualitative_hcl(h = c(0, 300, c = c(90, 90), l = 50), n=3) %>% magrittr::set_names(1:3))
  ) +
  labs(x = 'Item pair', y = 'Response', color = 'Unit', linetype = 'Unit sign') +
  theme(axis.text.x = element_text(angle=90), strip.background = element_blank(),
  strip.text.x = element_blank()) +
  scale_y_continuous(breaks = c(0, 1)) +
  guides(color = guide_none())
fig_j
```

```{r}
design <- "1255\n3455\n6667"
fig_1 <-
  ((wrap_elements(grid::textGrob('Network'))+theme_princti()) + fig_error + fig_margin + fig_acc + fig_gen) +
  plot_layout(guides = 'keep', design = '125\n345', widths = c(1,1,2.5))
fig <-
  ((fig_1/(
    ((fig_g / fig_h) | fig_i | fig_j) + plot_layout(nrow=1, widths=c(0.6,2,1))
  )) +
  plot_layout(heights = c(2,1)) +
  plot_annotation(tag_levels = 'a')) &
  theme(
    legend.key.size = unit(4, 'pt'),
    plot.margin = unit(c(0,0,0,0), 'pt'),
    legend.box.margin = unit(c(0,0,0,0), 'pt'),
    legend.box.spacing=unit(0, 'pt')
  )
frac <- 0.95
width <- 15.11078
fig
ggsave('../figures/fig-rich/fig-rich-raw-v2.pdf', width=frac*width, height=(4.5)/7*frac*width, units = "cm")
```


```{r}
dat <-
  clusters %>%
  filter(symmetric_input_weights=='False', scaling=='1e-32', n==7, n_clusters==3) %>%
  rename(order=arg) %>%
  mutate(item=j+1,unit = as.character(1+dim0%%n_clusters), value=array/(2*n_clusters)/sqrt(2)) %>%
  select(-dim0, -dim1, -n, -array, -j)
inner_join(
  dat %>% rename(seed1=seed, unit1=unit, value1=value),
  dat %>% rename(seed2=seed, unit2=unit, value2=value)
) %>%
  group_by(seed1, seed2, unit1, unit2, sign) %>%
  summarise(
    mismatch = sum((value1-value2)**2)
  ) %>%
  group_by(seed1, seed2, unit1, sign) %>%
  summarise(unit = unit2[which.min(mismatch)], mismatch=min(mismatch)) %>%
  filter(seed1!=seed2) %>%
  ggplot(aes(mismatch)) +
  geom_histogram()
assignment <-
  inner_join(
    dat %>% rename(seed1=seed, unit1=unit, value1=value),
    dat %>% rename(seed2=seed, unit2=unit, value2=value)
  ) %>%
  group_by(seed1, seed2, unit1, unit2, sign) %>%
  summarise(
    mismatch = sum((value1-value2)**2)
  ) %>%
  group_by(seed1, seed2, unit1, sign) %>%
  summarise(unit = unit2[which.min(mismatch)]) %>%
  filter(seed1==0) %>%
  ungroup() %>%
  select(-seed1) %>%
  rename(std_unit=unit1, seed=seed2)
assignment
```

```{r}
fig_c_1_1 <-
  clusters %>%
    filter(symmetric_input_weights=='False', scaling=='1e-32', n==7, sign==1, n_clusters==3) %>%
    rename(order=arg) %>%
    mutate(item=j+1,unit = as.character(1+dim0%%n_clusters), value=array/(2*n_clusters)/sqrt(2)) %>%
    inner_join(assignment) %>%
  mutate(
    item = map_chr(item, ~LETTERS[.]),
    assignment = if_else(std_unit %in% c('1', 'p1+'), 'p1+', 'p2+'),
    unit = factor(unit),
    order = if_else(order == 'first', 'first item', 'second item')
  ) %>%
  filter(order == 'first item') %>%
  arrange(desc(unit)) %>%
  ggplot(aes(item, value, color=factor(std_unit), group=paste(std_unit,order))) +
  stat_summary(geom='ribbon', color=NA, alpha=0.3, fill='grey', show.legend=FALSE, fun.ymin = function(x) mean(x)-sd(x), fun.ymax = function(x) mean(x)+sd(x)) +
  stat_summary(geom='line', show.legend=TRUE) +
  #stat_summary(geom='point', show.legend=FALSE) +
  theme_princti() +
  scale_color_manual(
    values = c(colorspace::qualitative_hcl(h = c(0, 240, c = c(90, 90), l = 50), n=3))
  ) +
  guides(color=guide_none()) +
  labs(x = 'Item 1', y = 'Weight', color = 'Unit') +
  scale_y_continuous(breaks=c(-0.5, 0, 0.5))
fig_c_1_2 <-
  clusters %>%
    filter(symmetric_input_weights=='False', scaling=='1e-32', n==7, sign==1, n_clusters==3) %>%
    rename(order=arg) %>%
    mutate(item=j+1,unit = as.character(1+dim0%%n_clusters), value=array/(2*n_clusters)/sqrt(2)) %>%
    inner_join(assignment) %>%
  mutate(
    item = map_chr(item, ~LETTERS[.]),
    assignment = if_else(std_unit %in% c('1', 'p1+'), 'p1+', 'p2+'),
    unit = factor(unit),
    order = if_else(order == 'first', 'first item', 'second item')
  ) %>%
  filter(order == 'second item') %>%
  arrange(desc(unit)) %>%
  ggplot(aes(item, value, color=factor(std_unit), group=paste(std_unit,order))) +
  stat_summary(geom='ribbon', color=NA, alpha=0.3, fill='grey', show.legend=FALSE, fun.ymin = function(x) mean(x)-sd(x), fun.ymax = function(x) mean(x)+sd(x)) +
  stat_summary(geom='line', show.legend=TRUE) +
  #stat_summary(geom='point', show.legend=FALSE) +
  theme_princti() +
  scale_color_manual(
    values = c(colorspace::qualitative_hcl(h = c(0, 240, c = c(90, 90), l = 50), n=3))
  ) +
  guides(color=guide_none()) +
  labs(x = 'Item 2', y = 'Weight', color = 'Unit') +
  scale_y_continuous(breaks=c(-0.5, 0, 0.5))
fig_c_1 <- fig_c_1_1 / fig_c_1_2
fig_c_1
```

```{r}
fig_c_2 <-
  clusters %>%
  filter(symmetric_input_weights=='False', scaling=='1e-32', n==7, n_clusters==3) %>%
  rename(order=arg) %>%
  mutate(item=j+1,unit = as.character(1+dim0%%n_clusters), value=array/(2*n_clusters)/sqrt(2)) %>%
  inner_join(assignment) %>%
  group_by(sign, std_unit, seed) %>%
  nest() %>%
  mutate(data = map(data, function(dat) {
    expand.grid(j1=1:7, j2=1:7) %>%
      inner_join(
        dat %>%
          filter(order=='first') %>%
          transmute(arr1=value, j1=item)
      ) %>%
      inner_join(
        dat %>%
          filter(order == 'second') %>%
          transmute(arr2=value, j2=item)
      ) %>%
      mutate(
        value = arr1+arr2,
        value = if_else(value>=0, value, 0)
      ) %>%
      select(j1, j2, value)
  })) %>%
  unnest() %>%
  mutate(value = sign*value) %>%
  filter(j2==j1+1) %>%
  mutate(
    label = map2_chr(j1, j2, ~paste0(LETTERS[..1], LETTERS[..2])),
    assignment = if_else(std_unit %in% c('1', 'p1+'), 'p1+', 'p2+'),
    unit = factor(std_unit)
  ) %>%
  ggplot(aes(label, value, color=unit, group=paste(unit,sign), linetype=factor(sign, levels=c(1,-1)))) +
  stat_summary(geom='ribbon', color=NA, alpha=0.3, fill='grey', show.legend=FALSE, fun.ymin = function(x) mean(x)-sd(x), fun.ymax = function(x) mean(x)+sd(x)) +
  stat_summary(geom='line', show.legend=TRUE) +
  #stat_summary(geom='point', show.legend=FALSE) +
  theme_princti() +
  scale_color_manual(
    values = c(c(`p1+` = 'black', `p2+` = 'grey40'), colorspace::qualitative_hcl(h = c(0, 240, c = c(90, 90), l = 50), n=3) %>% magrittr::set_names(1:3))
  ) +
  labs(x = 'Item pair', y = 'Response', color = 'Unit', linetype = 'Unit sign') +
  theme(axis.text.x = element_text(angle=90, vjust=0.5), strip.background = element_blank(),
  strip.text.x = element_blank()) +
  scale_y_continuous(breaks = c(0, 1)) +
  guides(color = guide_none())
fig_c_2
```

```{r}
colorspace::qualitative_hcl(h = c(0, 300, c = c(90, 90), l = 50), n=3)
```

```{r}
colorspace::qualitative_hcl(h = c(0, 300, c = c(90, 90), l = 50), n=4)
```

```{r}
fig_8_c <-
  (wrap_elements(grid::textGrob('Network'))+theme_princti()) + fig_c_1 + fig_c_2 + plot_layout(design='12\n32')
fig_8_c
```

```{r}
fig_d_1_1 <-
  get_p_network(7) %>%
      filter(unit %in% c('p1+', 'p2+')) %>%
      mutate(std_unit = unit) %>%
  mutate(
    item = map_chr(item, ~LETTERS[.]),
    assignment = if_else(std_unit %in% c('1', 'p1+'), 'p1+', 'p2+'),
    unit = factor(unit),
    order = if_else(order == 'first', 'first item', 'second item')
  ) %>%
  arrange(desc(unit)) %>%
  filter(order == 'first item') %>%
  ggplot(aes(item, value, color=factor(std_unit), group=paste(std_unit,order))) +
  stat_summary(geom='ribbon', color=NA, alpha=0.3, fill='grey', show.legend=FALSE, fun.ymin = function(x) mean(x)-sd(x), fun.ymax = function(x) mean(x)+sd(x)) +
  stat_summary(geom='line', show.legend=TRUE) +
  #stat_summary(geom='point', show.legend=FALSE) +
  facet_wrap(~order, ncol=1) +
  theme_princti() +
  scale_color_manual(
    values = c('black', 'grey40')
  ) +
  guides(color=guide_none()) +
  labs(x = 'Item 1', y = 'Weight', color = 'Unit') +
  scale_y_continuous(breaks=c(-0.5, 0, 0.5))
fig_d_1_2 <-
  get_p_network(7) %>%
      filter(unit %in% c('p1+', 'p2+')) %>%
      mutate(std_unit = unit) %>%
  mutate(
    item = map_chr(item, ~LETTERS[.]),
    assignment = if_else(std_unit %in% c('1', 'p1+'), 'p1+', 'p2+'),
    unit = factor(unit),
    order = if_else(order == 'first', 'first item', 'second item')
  ) %>%
  filter(order == 'second item') %>%
  arrange(desc(unit)) %>%
  ggplot(aes(item, value, color=factor(std_unit), group=paste(std_unit,order))) +
  stat_summary(geom='ribbon', color=NA, alpha=0.3, fill='grey', show.legend=FALSE, fun.ymin = function(x) mean(x)-sd(x), fun.ymax = function(x) mean(x)+sd(x)) +
  stat_summary(geom='line', show.legend=TRUE) +
  #stat_summary(geom='point', show.legend=FALSE) +
  theme_princti() +
  scale_color_manual(
    values = c('black', 'grey40')
  ) +
  guides(color=guide_none()) +
  labs(x = 'Item 2', y = 'Weight', color = 'Unit') +
  scale_y_continuous(breaks=c(-0.5, 0, 0.5))
fig_d_1 <-
  fig_d_1_1 / fig_d_1_2
fig_d_1
```

```{r}
fig_d_2 <-
  get_p_network(7) %>%
      filter(unit %in% c('p1+', 'p2+')) %>%
      mutate(std_unit = unit) %>%
  group_by(sign, std_unit) %>%
  nest() %>%
  mutate(data = map(data, function(dat) {
    expand.grid(j1=1:7, j2=1:7) %>%
      inner_join(
        dat %>%
          filter(order=='first') %>%
          transmute(arr1=value, j1=item)
      ) %>%
      inner_join(
        dat %>%
          filter(order == 'second') %>%
          transmute(arr2=value, j2=item)
      ) %>%
      mutate(
        value = arr1+arr2,
        value = if_else(value>=0, value, 0)
      ) %>%
      select(j1, j2, value)
  })) %>%
  unnest() %>%
  mutate(value = sign*value) %>%
  filter(j2==j1+1) %>%
  mutate(
    label = map2_chr(j1, j2, ~paste0(LETTERS[..1], LETTERS[..2])),
    assignment = if_else(std_unit %in% c('1', 'p1+'), 'p1+', 'p2+'),
    unit = factor(std_unit)
  ) %>%
  ggplot(aes(label, value, color=unit, group=paste(unit,sign), linetype=factor(sign, levels=c(1,-1)))) +
  stat_summary(geom='ribbon', color=NA, alpha=0.3, fill='grey', show.legend=FALSE, fun.ymin = function(x) mean(x)-sd(x), fun.ymax = function(x) mean(x)+sd(x)) +
  stat_summary(geom='line', show.legend=TRUE) +
  #stat_summary(geom='point', show.legend=FALSE) +
  theme_princti() +
  scale_color_manual(
    values = c(c(`p1+` = 'black', `p2+` = 'grey40'), colorspace::qualitative_hcl(h = c(0, 300, c = c(90, 90), l = 50), n=3) %>% magrittr::set_names(1:3))
  ) +
  labs(x = 'Item pair', y = 'Response', color = 'Unit', linetype = 'Unit sign') +
  theme(axis.text.x = element_text(angle=90, vjust=0.5), strip.background = element_blank(),
  strip.text.x = element_blank()) +
  scale_y_continuous(breaks = c(0, 1)) +
  guides(color = guide_none())
fig_d_2
```

```{r}
fig_8_d <-
  (wrap_elements(grid::textGrob('Network'))+theme_princti()) + fig_d_1 + fig_d_2 + plot_layout(design='12\n32')
fig_8_d
```

```{r}
fig_8_f <-
  bind_rows(
  dnn_norms_2 %>%
    mutate(
      type = if_else(symmetric_input_weights=='True', 'symmetric', 'standard'),
      network='empirical',
      norm = l2/sqrt(2)
    ),
  tibble(
    n = 5:15
  ) %>%
    mutate(
      data = map(
        n,
        function(n) {
          get_p_network(n) %>%
          mutate(network='hand-constructed', type = 'periodic')
        }
      )
    ) %>%
    unnest() %>%
    group_by(network, unit, n, type) %>%
    summarise(norm = sqrt(sum(value**2))) %>%
    group_by(network, n, type) %>%
    summarise(norm = 2*sum(norm)),
  tibble(n = 5:15, norm = 2*sqrt(6)/3*sqrt((5:15)*((5:15)**2-1)), network='hand-constructed', type='rank')
) %>%
  filter(type != 'symmetric') %>%
  ggplot(aes(n, norm, color = type, group=paste(type, network))) + 
  stat_summary(geom='ribbon', color=NA, alpha=0.3, show.legend=FALSE, fun.ymin = function(x) mean(x)-sd(x), fun.ymax = function(x) mean(x)+sd(x)) +
  stat_summary(geom='line', show.legend=TRUE) +
  theme_princti() +
  scale_color_manual(
    values = c(rank = 'darkorchid4', periodic = 'black', standard = '#cc9f28ff'),
    breaks = c('standard', 'periodic', 'rank'),
    labels = c('empirical', 'hand-constructed', 'rank')
  ) +
  labs(x = 'n', y = 'Norm', linetype=NULL, color=NULL) +
  scale_x_continuous(breaks = c(5,10,15)) +
  scale_y_continuous(breaks=c(25, 75))
fig_8_f
```

```{r}
fig_8_e <-
  expand.grid(
    item = 1:7,
    order = c('first', 'second')
  ) %>%
  tibble() %>%
  mutate(
    value = if_else(order == 'first', 1, -1)*(3:-3)
  ) %>%
  ggplot(aes(item, value, linetype = order)) +
  geom_line(color='darkorchid4') +
  theme_princti() +
  scale_linetype_manual(values = c('solid', '11')) +
  scale_x_continuous(breaks = 1:7, labels = c('A', '', '', 'D', '', '', 'G'), minor_breaks = 1:7) +
  labs(x = 'Item', y = 'Weight')
fig_8_e
```

```{r}
row_1 <- ((fig_g/fig_h)|fig_8_c) + plot_layout(widths=c(0.6, 2))
row_2 <- (fig_8_d|(fig_8_e/fig_8_f)) + plot_layout(widths=c(2, 0.6))
((row_1/row_2) +
  plot_annotation(tag_levels = c('a',''))) &
  theme(
    legend.key.size = unit(4, 'pt'),
    plot.margin = unit(c(0,0,0,0), 'pt'),
    legend.box.margin = unit(c(0,0,0,0), 'pt'),
    legend.box.spacing=unit(0, 'pt'), 
    legend.position=c(1,1), strip.background = element_blank(),
  strip.text.x = element_blank()
  )
frac <- 0.95
width <- 15.11078
ggsave('../figures/fig-rich/fig-rich-revision-v2-raw.pdf', width=frac*width*0.6, height=4/7*frac*width, units = "cm")
```


```{r}
fig_i <-
  bind_rows(
    clusters %>%
      filter(symmetric_input_weights=='False', scaling=='1e-32', n==7, sign==1, n_clusters==3) %>%
      rename(order=arg) %>%
      mutate(item=j+1,unit = as.character(1+dim0%%n_clusters), value=array/(2*n_clusters)/sqrt(2)) %>%
      inner_join(assignment),
    get_p_network(7) %>%
      filter(unit %in% c('p1+', 'p2+')) %>%
      mutate(std_unit = unit)
  ) %>%
  mutate(
    item = map_chr(item, ~LETTERS[.]),
    assignment = if_else(std_unit %in% c('1', 'p1+'), 'p1+', 'p2+'),
    unit = factor(unit)
  ) %>%
  arrange(desc(unit)) %>%
  ggplot(aes(item, value, color=factor(std_unit), group=paste(std_unit,order))) +
  stat_summary(geom='ribbon', color=NA, alpha=0.3, fill='grey', show.legend=FALSE, fun.ymin = function(x) mean(x)-sd(x), fun.ymax = function(x) mean(x)+sd(x)) +
  stat_summary(geom='line', show.legend=TRUE) +
  #stat_summary(geom='point', show.legend=FALSE) +
  facet_grid(assignment~order) +
  theme_princti() +
  theme(strip.background = element_blank(),
  strip.text.x = element_blank()) +
  scale_color_manual(
    values = c(c(`p1+` = 'black', `p2+` = 'grey40'), colorspace::qualitative_hcl(h = c(0, 300, c = c(90, 90), l = 50), n=3) %>% magrittr::set_names(1:3))
  ) +
  labs(x = 'Item', y = 'Weight', color = 'Unit')
fig_i
```

```{r}
fig_j <-
  bind_rows(
    clusters %>%
      filter(symmetric_input_weights=='False', scaling=='1e-32', n==7, n_clusters==3) %>%
      rename(order=arg) %>%
      mutate(item=j+1,unit = as.character(1+dim0%%n_clusters), value=array/(2*n_clusters)/sqrt(2)) %>%
      inner_join(assignment),
    get_p_network(7) %>%
      mutate(std_unit = unit) %>%
      filter(unit %in% c('p1+', 'p2+'))
  ) %>%
  group_by(sign, std_unit, seed) %>%
  nest() %>%
  mutate(data = map(data, function(dat) {
    expand.grid(j1=1:7, j2=1:7) %>%
      inner_join(
        dat %>%
          filter(order=='first') %>%
          transmute(arr1=value, j1=item)
      ) %>%
      inner_join(
        dat %>%
          filter(order == 'second') %>%
          transmute(arr2=value, j2=item)
      ) %>%
      mutate(
        value = arr1+arr2,
        value = if_else(value>=0, value, 0)
      ) %>%
      select(j1, j2, value)
  })) %>%
  unnest() %>%
  mutate(value = sign*value) %>%
  filter(j2==j1+1) %>%
  mutate(
    label = map2_chr(j1, j2, ~paste0(LETTERS[..1], LETTERS[..2])),
    assignment = if_else(std_unit %in% c('1', 'p1+'), 'p1+', 'p2+'),
    unit = factor(std_unit)
  ) %>%
  ggplot(aes(label, value, color=unit, group=paste(unit,sign), linetype=factor(sign, levels=c(1,-1)))) +
  stat_summary(geom='ribbon', color=NA, alpha=0.3, fill='grey', show.legend=FALSE, fun.ymin = function(x) mean(x)-sd(x), fun.ymax = function(x) mean(x)+sd(x)) +
  stat_summary(geom='line', show.legend=TRUE) +
  #stat_summary(geom='point', show.legend=FALSE) +
  facet_wrap(~assignment, ncol=1) +
  theme_princti() +
  scale_color_manual(
    values = c(c(`p1+` = 'black', `p2+` = 'grey40'), colorspace::qualitative_hcl(h = c(0, 300, c = c(90, 90), l = 50), n=3) %>% magrittr::set_names(1:3))
  ) +
  labs(x = 'Item pair', y = 'Response', color = 'Unit', linetype = 'Unit sign') +
  theme(axis.text.x = element_text(angle=90), strip.background = element_blank(),
  strip.text.x = element_blank()) +
  scale_y_continuous(breaks = c(0, 1)) +
  guides(color = guide_none())
fig_j
```



```{r}
inertia %>%
  filter(symmetric_input_weights == 'False', cl<=10, n==7) %>%
  mutate(
    inertia = if_else(cl==0, 1., inertia),
    scaling = case_when(
      scaling == '1.0' ~ 'Lazy',
      scaling == '1e-32' ~ 'Rich'
    ) %>%
      factor(
        levels = scaling_levels
      )
  ) %>%
  ggplot(aes(2*cl, mismatch, color=scaling, fill=scaling, group=scaling, fill=scaling)) +
  stat_summary(geom='ribbon', color=NA, alpha=0.3, show.legend=FALSE, fun.ymin = function(x) mean(x)-sd(x), fun.ymax = function(x) mean(x)+sd(x)) +
  stat_summary(geom='line', show.legend=TRUE) +
  theme_princti() +
  labs(x = '# Clusters', y = 'Inertia', color = NULL, fill=NULL) +
  scale_color_manual(values = scaling_palette[2:4], drop = TRUE) +
  scale_fill_manual(values = scaling_palette[2:4], drop = TRUE) +
  scale_x_continuous(breaks = c(6, 20)) +
  scale_y_log10()
```


```{r}
get_p_network(7) %>%
  filter(unit %in% c('p1+', 'p2+')) %>%
  ggplot(aes(item, value, alpha=order, fill=unit)) +
  geom_col(position='dodge')
```

```{r}
bind_rows(
  clusters %>%
    filter(symmetric_input_weights=='False', scaling=='1e-32', n==7, sign==1, n_clusters==3, seed==0) %>%
    rename(order=arg) %>%
    mutate(item=j+1,unit = as.character(1+dim0%%n_clusters), value=array/(2*n_clusters)/sqrt(2)),
  get_p_network(7) %>%
    filter(unit %in% c('p1+', 'p2+'))
) %>%
  ggplot(aes(item, value, color=factor(unit), linetype=order)) +
  geom_point() +
  geom_line() +
  facet_grid(order~(unit%in%c('1', 'p1+')))
```




```{r}
bind_rows(
  clusters %>%
    filter(symmetric_input_weights=='False', scaling=='1e-32', n==15, sign==1, n_clusters==3, seed==1) %>%
    rename(order=arg) %>%
    mutate(item=j+1,unit = as.character(1+dim0%%n_clusters), value=array/(2*n_clusters)/sqrt(2)),
  get_p_network(15) %>%
    filter(unit %in% c('p1+', 'p2+'))
) %>%
  ggplot(aes(item, value, color=factor(unit), linetype=order)) +
  geom_point() +
  geom_line() +
  facet_grid(order~(unit%in%c('1', 'p1+')))
```


```{r}
bind_rows(
  clusters %>%
    filter(symmetric_input_weights=='False', scaling=='1e-32', n==7, n_clusters==3, seed==0) %>%
    rename(order=arg) %>%
    mutate(item=j+1,unit = as.character(1+dim0%%n_clusters), value=array/(2*n_clusters)/sqrt(2), network='empirical'),
  get_p_network(7) %>%
    mutate(network='hand-constructed')
) %>%
  group_by(sign, unit, network) %>%
  nest() %>%
  mutate(data = map(data, function(dat) {
    expand.grid(j1=1:7, j2=1:7) %>%
      inner_join(
        dat %>%
          filter(order=='first') %>%
          transmute(arr1=value, j1=item)
      ) %>%
      inner_join(
        dat %>%
          filter(order == 'second') %>%
          transmute(arr2=value, j2=item)
      ) %>%
      mutate(
        value = arr1+arr2,
        value = if_else(value>=0, value, 0)
      ) %>%
      select(j1, j2, value)
  })) %>%
  unnest() %>%
  mutate(value = sign*value) %>%
  filter(j2==j1+1) %>%
  mutate(
    label = map2_chr(j1, j2, ~paste0(LETTERS[..1], LETTERS[..2]))
  ) %>%
  ggplot(aes(label, value, color=unit, group=paste(unit,sign), linetype=factor(sign, levels=c(1,-1)))) +
  geom_line() +
  facet_wrap(~network)
```

```{r}
bind_rows(
  clusters %>%
    filter(symmetric_input_weights=='False', scaling=='1e-32', n==15, n_clusters==3, seed==1) %>%
    rename(order=arg) %>%
    mutate(item=j+1,unit = as.character(1+dim0%%n_clusters), value=array/(2*n_clusters)/sqrt(2), network='empirical'),
  get_p_network(15) %>%
    mutate(network='hand-constructed', n = 15)
) %>%
  group_by(sign, unit, network, n) %>%
  nest() %>%
  mutate(data = map2(data, n, function(dat, n) {
    expand.grid(j1=1:n, j2=1:n) %>%
      inner_join(
        dat %>%
          filter(order=='first') %>%
          transmute(arr1=value, j1=item)
      ) %>%
      inner_join(
        dat %>%
          filter(order == 'second') %>%
          transmute(arr2=value, j2=item)
      ) %>%
      mutate(
        value = arr1+arr2,
        value = if_else(value>=0, value, 0)
      ) %>%
      select(j1, j2, value)
  })) %>%
  unnest() %>%
  mutate(value = sign*value) %>%
  filter(j2==j1+1) %>%
  mutate(
    label = map2_chr(j1, j2, ~paste0(LETTERS[..1], LETTERS[..2]))
  ) %>%
  ggplot(aes(label, value, color=unit, group=paste(unit,sign), linetype=factor(sign, levels=c(1,-1)))) +
  geom_line() +
  facet_wrap(~network)
```


```{r}
dat <-
  bind_rows(
  clusters %>%
    filter(symmetric_input_weights=='False', scaling=='1e-32', n==7, n_clusters==3, seed==0) %>%
    rename(order=arg) %>%
    mutate(item=j+1,unit = as.character(1+dim0%%n_clusters), value=array/(2*n_clusters)/sqrt(2), network='empirical'),
  get_p_network(7) %>%
    mutate(network='hand-constructed')
) %>%
  group_by(sign, unit, network) %>%
  nest() %>%
  mutate(data = map(data, function(dat) {
    expand.grid(j1=1:7, j2=1:7) %>%
      inner_join(
        dat %>%
          filter(order=='first') %>%
          transmute(arr1=value, j1=item)
      ) %>%
      inner_join(
        dat %>%
          filter(order == 'second') %>%
          transmute(arr2=value, j2=item)
      ) %>%
      mutate(
        value = arr1+arr2,
        value = if_else(value>=0, value, 0)
      ) %>%
      select(j1, j2, value)
  })) %>%
  unnest() %>%
  mutate(value = sign*value)
bind_rows(
    dat, 
    dat %>%
      group_by(network, j1, j2) %>%
      summarise(value=sum(value)) %>%
      mutate(unit = 'sum', sign=1)
  ) %>%
  filter(j2>j1) %>%
  mutate(
    label = map2_chr(j1, j2, ~paste0(LETTERS[..1], LETTERS[..2]))
  ) %>%
  ggplot(aes(label, value, color=unit, group=paste(unit,sign), linetype=factor(sign, levels=c(1,-1)))) +
  geom_line() +
  facet_grid(network~abs(j1-j2), space = 'free_x', scales = 'free_x')
```

```{r}
dat <-
  bind_rows(
  clusters %>%
    filter(symmetric_input_weights=='False', scaling=='1e-32', n==15, n_clusters==3, seed==1) %>%
    rename(order=arg) %>%
    mutate(item=j+1,unit = as.character(1+dim0%%n_clusters), value=array/(2*n_clusters)/sqrt(2), network='empirical'),
  get_p_network(15) %>%
    mutate(network='hand-constructed', n=15)
) %>%
  group_by(sign, unit, network, n) %>%
  nest() %>%
  mutate(data = map2(data, n, function(dat, n) {
    expand.grid(j1=1:n, j2=1:n) %>%
      inner_join(
        dat %>%
          filter(order=='first') %>%
          transmute(arr1=value, j1=item)
      ) %>%
      inner_join(
        dat %>%
          filter(order == 'second') %>%
          transmute(arr2=value, j2=item)
      ) %>%
      mutate(
        value = arr1+arr2,
        value = if_else(value>=0, value, 0)
      ) %>%
      select(j1, j2, value)
  })) %>%
  unnest() %>%
  mutate(value = sign*value)
bind_rows(
    dat, 
    dat %>%
      group_by(network, j1, j2) %>%
      summarise(value=sum(value)) %>%
      mutate(unit = 'sum', sign=1)
  ) %>%
  filter(j2>j1) %>%
  mutate(
    label = map2_chr(j1, j2, ~paste0(LETTERS[..1], LETTERS[..2]))
  ) %>%
  ggplot(aes(label, value, color=unit, group=paste(unit,sign), linetype=factor(sign, levels=c(1,-1)))) +
  geom_line() +
  facet_grid(network~abs(j1-j2), space = 'free_x', scales = 'free_x')
```


```{r}
bind_rows(
  clusters %>%
    filter(symmetric_input_weights=='False', scaling=='1e-32', n==7, sign==1, n_clusters==3, seed==0) %>%
    rename(order=arg) %>%
    mutate(item=j+1,unit = as.character(1+dim0%%n_clusters), value=array/(2*n_clusters)/sqrt(2), network='empirical'),
  get_p_network(7) %>%
    filter(unit %in% c('p1+', 'p2+')) %>%
    mutate(network='hand-constructed')
) %>%
  group_by(network, unit) %>%
  summarise(norm = sqrt(sum(value**2)))
```

```{r}
bind_rows(
  clusters %>%
    filter(symmetric_input_weights=='False', scaling=='1e-32', n==7, sign==-1, n_clusters==3, seed==0) %>%
    rename(order=arg) %>%
    mutate(item=j+1,unit = as.character(1+dim0%%n_clusters), value=array/6/sqrt(2)),
  get_p_network(7) %>%
    filter(unit %in% c('p1-', 'p2-'))
) %>%
  ggplot(aes(item, value, color=factor(unit), linetype=order)) +
  geom_point() +
  geom_line() +
  facet_grid(order~(unit%in%c('1', 'p1-')))
```


```{r}
design <- "1255\n3455\n6667"
fig_1 <-
  ((wrap_elements(grid::textGrob('Network'))+theme_princti()) + fig_error + fig_margin + fig_acc + fig_gen) +
  plot_layout(guides = 'keep', design = '125\n345', widths = c(1,1,2.5))
fig <-
  ((fig_1/similarity) +
  plot_layout(heights = c(2,1)) +
  plot_annotation(tag_levels = 'a')) &
  theme(
    legend.key.size = unit(4, 'pt'),
    plot.margin = unit(c(0,0,0,0), 'pt'),
    legend.box.margin = unit(c(0,0,0,0), 'pt'),
    legend.box.spacing=unit(0, 'pt')
  )
frac <- 0.95
width <- 15.11078
fig
ggsave('../figures/fig-rich/fig-rich-raw.pdf', width=frac*width, height=4.5/7*frac*width, units = "cm")
```

```{r}
fig_k <-
  bind_rows(
    dnn_norms %>% filter(scaling == 1e-16) %>%
      mutate(type = case_when(
        weight_structure == 'dense' ~ 'Standard',
        weight_structure == 'symmetric' ~ 'Symmetric/O-network',
        weight_structure == 'modular' ~ 'Modular/R-network'
      ), type2 = 'Trained networks') %>%
      rename(norm = l2),
    inertia %>%
      filter(weight_structure=='dense', cl==3, scaling==1e-16) %>%
      mutate(
        type = 'Standard',
        type2 = 'Schematic networks'
      ),
    tibble(
      type = c('Symmetric/O-network', 'Modular/R-network'),
      norm = 8*sqrt(14),
      type2 = 'Schematic networks'
    )
  ) %>%
  mutate(
    type = factor(type, levels = c('Standard', 'Symmetric/O-network', 'Modular/R-network')),
    type2 = factor(type2, levels = c('Trained networks', 'Schematic networks'))
  ) %>%
  ggplot(aes(x = type2, y = norm, fill = type)) +
  stat_summary(geom='col', position = 'dodge') +
  scale_fill_manual(
    breaks = c('Standard', 'Symmetric/O-network', 'Modular/R-network'), 
    values = c(scaling_palette[4], hcl.colors(3, 'Dark 3')[c(1,3)]),
    labels = c('Standard', 'Symmetric/\nO-network', 'Modular/\nR-network')
  ) +
  theme_princti() +
  labs(x = 'Network type', y = 'Norm', fill = NULL) +
  scale_y_continuous(breaks = c(0, 50)) +
  scale_x_discrete(labels = c('Trained', 'Schematic'))
fig_k
```

```{r}
clusters %>%
  filter(seed==0, n_clusters==3, scaling==1e-16, weight_structure=='dense') %>%
  mutate(array = array/2/sqrt(2)/n_clusters, cl_dim = dim0 %% n_clusters) %>%
  group_by(sign, cl_dim) %>%
  nest() %>%
  mutate(data = map(data, function(dat) {
    expand.grid(j1=0:6, j2=0:6) %>%
      inner_join(
        dat %>%
          filter(arg=='first') %>%
          transmute(arr1=array, j1=j)
      ) %>%
      inner_join(
        dat %>%
          filter(arg == 'second') %>%
          transmute(arr2=array, j2=j)
      ) %>%
      mutate(
        value = arr1+arr2,
        value = if_else(value>=0, value, 0)
      ) %>%
      select(j1, j2, value)
  })) %>%
  unnest() %>%
  mutate(
    value = sign*value,
    label = map2_chr(j1, j2, ~paste0(min(LETTERS[..1+1],LETTERS[..2+1]), max(LETTERS[..1+1], LETTERS[..2+1]))),
    symbolic_distance=abs(j2-j1),
    j1 = map_chr(j1, ~LETTERS[.+1]),
    j2 = map_chr(j2, ~LETTERS[.+1])
  ) %>%
  ggplot(aes(j1, j2, fill = value)) +
  geom_tile() +
  facet_grid(sign~cl_dim) +
  scico::scale_fill_scico(palette='vik')
```

```{r}
clusters %>%
  filter(seed==0, n_clusters==3, scaling==1e-16, weight_structure=='dense', sign==1) %>%
  mutate(array = array/2/sqrt(2)/n_clusters, cl_dim = dim0 %% n_clusters) %>%
  mutate(
    j = map_chr(j, ~LETTERS[.+1])
  ) %>%
  ggplot(aes(j, array, fill=factor(cl_dim), group=paste(arg, cl_dim))) +
  geom_line(position='dodge') +
  facet_grid(seed~arg)
```

```{r}
clusters %>%
  filter(seed==0, n_clusters==1, scaling==1e-16, weight_structure=='symmetric', sign==1) %>%
  mutate(array = array/2/sqrt(2)/n_clusters, cl_dim = dim0 %% n_clusters) %>%
  mutate(
    j = map_chr(j, ~LETTERS[.+1])
  ) %>%
  ggplot(aes(j, array, fill=factor(cl_dim), group=paste(arg, cl_dim))) +
  geom_col(position='dodge') +
  facet_grid(seed~arg)
```


```{r}
clusters %>%
  filter(seed==0, n_clusters==1, scaling==1e-16, weight_structure=='symmetric') %>%
  mutate(array = array/2/sqrt(2)/n_clusters, cl_dim = dim0 %% n_clusters) %>%
  mutate(
    j = map_chr(j, ~LETTERS[.+1])
  ) %>%
  ggplot(aes(j, array, color=arg, group=arg)) +
  geom_line() +
  facet_grid(sign~cl_dim)
```


```{r}
clusters %>%
  filter(seed==0, n_clusters==3, scaling==1e-16, weight_structure=='dense') %>%
  mutate(array = array/2/sqrt(2)/n_clusters, cl_dim = dim0 %% n_clusters) %>%
  group_by(sign, cl_dim) %>%
  nest() %>%
  mutate(data = map(data, function(dat) {
    expand.grid(j1=0:6, j2=0:6) %>%
      inner_join(
        dat %>%
          filter(arg=='first') %>%
          transmute(arr1=array, j1=j)
      ) %>%
      inner_join(
        dat %>%
          filter(arg == 'second') %>%
          transmute(arr2=array, j2=j)
      ) %>%
      mutate(
        value = arr1+arr2,
        value = if_else(value>=0, value, 0)
      ) %>%
      select(j1, j2, value)
  })) %>%
  unnest() %>%
  mutate(
    value = sign(j2-j1)*sign*value,
    label = map2_chr(j1, j2, ~paste0(LETTERS[..1+1], LETTERS[..2+1])),
    symbolic_distance=(j1-j2),
    order = sign(j2-j1),
    j1 = map_chr(j1, ~LETTERS[.+1]),
    j2 = map_chr(j2, ~LETTERS[.+1])
  ) %>%
  filter(symbolic_distance != 0) %>%
  ggplot(aes(label, value, group=cl_dim, color=factor(cl_dim))) +
  geom_line() +
  facet_grid(sign~symbolic_distance, scales='free_x', space = 'free_x')
```


```{r}
clusters %>%
  filter(seed==0, n_clusters==3, scaling==1e-16, weight_structure=='dense') %>%
  mutate(array = array/2/sqrt(2)/n_clusters, cl_dim = dim0 %% n_clusters) %>%
  group_by(sign, cl_dim) %>%
  nest() %>%
  mutate(data = map(data, function(dat) {
    expand.grid(j1=0:6, j2=0:6) %>%
      inner_join(
        dat %>%
          filter(arg=='first') %>%
          transmute(arr1=array, j1=j)
      ) %>%
      inner_join(
        dat %>%
          filter(arg == 'second') %>%
          transmute(arr2=array, j2=j)
      ) %>%
      mutate(
        value = arr1+arr2,
        value = if_else(value>=0, value, 0)
      ) %>%
      select(j1, j2, value)
  })) %>%
  unnest() %>%
  mutate(
    value = sign*value,
    label = map2_chr(j1, j2, ~paste0(min(LETTERS[..1+1],LETTERS[..2+1]), max(LETTERS[..1+1], LETTERS[..2+1]))),
    symbolic_distance=abs(j2-j1),
    j1 = map_chr(j1, ~LETTERS[.+1]),
    j2 = map_chr(j2, ~LETTERS[.+1])
  ) %>%
  ggplot(aes(j1, j2, fill = value)) +
  geom_tile() +
  facet_grid(sign~cl_dim) +
  scico::scale_fill_scico(palette='vik')
```


```{r}
design <- "1255\n3455\n6667"
fig_1 <-
  ((wrap_elements(grid::textGrob('Network'))+theme_princti()) + fig_error + fig_margin + fig_acc + fig_gen) +
  plot_layout(guides = 'keep', design = '125\n345', widths = c(1,1,2.5))
fig <-
  ((fig_1/(
    fig_g + fig_h + (wrap_elements(grid::textGrob('O-network'))+theme_princti()) + (wrap_elements(grid::textGrob('R-network'))+theme_princti()) + fig_k + plot_layout(nrow=1)
  )) +
  plot_layout(heights = c(2,0.8)) +
  plot_annotation(tag_levels = 'a')) &
  theme(
    legend.key.size = unit(4, 'pt'),
    plot.margin = unit(c(0,0,0,0), 'pt'),
    legend.box.margin = unit(c(0,0,0,0), 'pt'),
    legend.box.spacing=unit(0, 'pt')
  )
frac <- 0.95
width <- 15.11078
fig
ggsave('../figures/fig-rich/fig-rich-raw.pdf', width=frac*width, height=(3*0.8*1.5)/7*frac*width, units = "cm")
```
